### ISSUE TITLE
extract_json_strings.py borked on optional bodyparts name

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#2978]
### Describe the bug

![](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/c7ea1cfe-0deb-4c54-87ce-c497eb4c279a "hecc")

[workflow](https://github.com/cataclysmbnteam/Cataclysm-BN/actions/workflows/push-translation-template.yml)

```
Run lang/update_pot.sh
> Extracting strings from json
==> Generating the list of all Git tracked files
==> Parsing JSON
----> Traversing directory data/help
----> Traversing directory data/json
Traceback (most recent call last):
  File "/home/runner/work/Cataclysm-BN/Cataclysm-BN/lang/extract_json_strings.py", line 1268, in <module>
    extract_all_from_dir(state, i)
  File "/home/runner/work/Cataclysm-BN/Cataclysm-BN/lang/extract_json_strings.py", line 1178, in extract_all_from_dir
    extract_all_from_file(state, full_name)
  File "/home/runner/work/Cataclysm-BN/Cataclysm-BN/lang/extract_json_strings.py", line 1200, in extract_all_from_file
    extract(state, jsonobject)
  File "/home/runner/work/Cataclysm-BN/Cataclysm-BN/lang/extract_json_strings.py", line 1001, in extract
    extract_specials[object_type](state, item)
  File "/home/runner/work/Cataclysm-BN/Cataclysm-BN/lang/extract_json_strings.py", line 231, in extract_bodypart
    writestr(state, item["heading_multiple"])
KeyError: 'heading_multiple'
Error in extract_json_strings.py. Aborting
Error: Process completed with exit code 1.
```

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/701016c78fe8f9a9261d6eb77e2774664afd3b6a/lang/extract_json_strings.py#L229-L231

#2775 made bodypart names like `heading_multiple` optional, however `extract_json_strings.py` doesn't know that and it's been secretly failing for a month.

### Steps To Reproduce

run `lang/update_pot.sh` from project root

### Additional context

originally reported in discord by [fruitybite](https://discord.com/channels/830879262763909202/1093580823351001098/1115667075101360188)

**Comment by scarf005** [comment]
cc @KheirFerrum
